Repository donga-it-club/past-forward-frontend, pull requests merged in 2024-03, with the labels that each got.

#19 #7 :lipstick: Design: Create 모달 UI 완성
  package.json
  src/App.tsx
  src/components/common/NavBar.tsx
  src/components/createRetro/CreateButtonBox.tsx
  src/components/createRetro/CreateModal.tsx
  src/components/createRetro/PersonalRetroCreateButton.tsx
  src/components/createRetro/StartDateCalender.tsx
  src/components/createRetro/TeamRetroCreateButton.tsx
  src/components/createRetro/TemplateSelect.tsx
  src/components/createRetro/UploadPhoto.tsx
  src/components/createRetro/test.tsx
  src/pages/CreateRetroPage.tsx
  src/pages/HomePage.tsx
  src/pages/TemplateNothingPage.tsx
  src/styles/fonts/GlobalFont.ts
  webpack.config.js
  yarn.lock
Labels: enhancement

#21 #12 ✨ Feat: 절대경로 설정 및 ErrorBoundary 적용
  .eslintrc.js
  .eslintrc.json
  package-lock.json
  src/App.tsx
  src/Index.tsx
  src/components/ErrorBoundary.tsx
  src/components/createRetro/PersonalRetroCreateButton.tsx
  src/components/createRetro/TeamRetroCreateButton.tsx
  src/pages/CreateRetroPage.tsx
  src/pages/HomePage.tsx
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: enhancement

#24 #23 [✨ Feature] creating common styled css
  src/index.css
  src/styles/fonts/Pretendard-ExtraBold.woff
  src/styles/fonts/Pretendard-ExtraLight.woff
  src/styles/fonts/Pretendard-SemiBold.woff
  yarn.lock
Labels: enhancement

#28 #8 :sparkles: Feat : WriteRetroTeamPage 컴포넌트 추가
  src/App.tsx
  src/assets/-group_senior.png
  src/assets/Avatar Image.png
  src/assets/Vector.png
  src/assets/access_alarms.png
  src/assets/message.png
  src/assets/thumb_up.png
  src/components/writeRetro/CheckPopUp.tsx
  src/components/writeRetro/Frame.tsx
  src/components/writeRetro/Label.tsx
  src/components/writeRetro/SaveButton.tsx
  src/components/writeRetro/Task.tsx
  src/components/writeRetro/WriteRetroActionItems.tsx
  src/components/writeRetro/WriteRetroKudos.tsx
  src/components/writeRetro/WriteRetroTitle.tsx
  src/components/writeRetro/WriteRetroToImprove.tsx
  src/components/writeRetro/WriteRetroWentWell.tsx
  src/pages/WriteRetroTeamPage.tsx
  src/styles/writeRetroStyles/CheckPopUp.style.ts
  src/styles/writeRetroStyles/Frame.style.ts
  src/styles/writeRetroStyles/Label.style.ts
  src/styles/writeRetroStyles/SaveButton.style.ts
  src/styles/writeRetroStyles/Task.style.ts
  src/styles/writeRetroStyles/WriteRetroTitle.style.ts
  webpack.config.js
Labels: documentation

#29 #9 :sparkles: Feat: RetroList 내부 상단바 생성
  src/assets/RetroListBoardViewIcon.png
  src/assets/RetroListLIstViewIcon.png
  src/assets/SearchIcon.png
  src/components/RetroListHaveSth/RetroListContentsFilter.tsx
  src/components/RetroListHaveSth/RetroListSearch.tsx
  src/components/RetroListHaveSth/RetroListSortButton.tsx
  src/pages/RetroListHaveSthPage.tsx
  yarn.lock
Labels: enhancement

#47 [FE][Feature] RetroList Nothing Page 퍼블리싱
  src/components/createRetro/CreateButtonBox.tsx
  src/components/createRetro/DescriptionBox.tsx
  src/components/createRetro/PersonalRetroDescription.tsx
  src/components/createRetro/TeamRetroDescription.tsx
  src/pages/CreateRetroPage.tsx
  src/styles/createRetro/CreateButtonBox.style.ts
  src/styles/createRetro/Description.style.ts
  src/styles/createRetro/DescriptionBox.style.ts
Labels: FE

#48 :sparkles: Feat: Task 컴포넌트 추가 (#38)
  public/index.html
  src/components/writeRetro/Message.tsx
  src/components/writeRetro/Task.tsx
  src/components/writeRetro/TaskMessage.tsx
  src/styles/writeRetroStyles/Message.style.ts
  src/styles/writeRetroStyles/Task.style.ts
  src/styles/writeRetroStyles/TaskMessage.style.ts
Labels: enhancement, FE

#55 #40 [Feature] RetroList 보드 뷰 레이아웃
  src/assets/BookmarkIcon_N.png
  src/assets/BookmarkIcon_Y.png
  src/assets/GroupIcon.png
  src/assets/IngIcon.png
  src/assets/MoreIcon.png
  src/assets/PersonalIcon.png
  src/assets/Thumbnail.png
  src/components/RetroListHaveSth/ContentsList.tsx
  src/components/RetroListHaveSth/RetroListContentsFilter.tsx
  src/components/RetroListHaveSth/RetroListSortButton.tsx
  src/components/RetroListHaveSth/RetroListViewButton.tsx
  src/pages/RetroListHaveSthPage.tsx
  src/styles/RetroListHaveSth/ContentsList.styles.ts
  src/styles/RetroListHaveSth/RetroListHaveSthPage.style.ts
Labels: FE

#56 [FE][Feature] CreateRetro Modal 퍼블리싱
  package.json
  src/assets/calendar_icon.svg
  src/components/createRetro/CreateButtonBox.tsx
  src/components/createRetro/CreateModal.tsx
  src/components/createRetro/StartDateCalender.tsx
  src/components/createRetro/TemplateSelect.tsx
  src/components/createRetro/UploadPhoto.tsx
  src/components/createRetro/modal/CreateModal.tsx
  src/components/createRetro/modal/ImageUpload.tsx
  src/components/createRetro/modal/StartDateCalender.tsx
  src/components/createRetro/modal/TemplateSelect.tsx
  src/components/createRetro/modal/TitleInput.tsx
  src/pages/CreateRetroPage.tsx
  src/styles/createRetro/CreateModal.style.ts
  src/styles/createRetro/modal/Calendar.css
  src/styles/createRetro/modal/CreateModal.style.ts
  src/styles/createRetro/modal/StartDateCalendar.style.ts
  yarn.lock
Labels: FE

#62 :sparkles : Feat: Task Message 추가 (#49)
  src/assets/PlusIcon_black.png
  src/assets/PlusIcon_gray.png
  src/components/writeRetro/AddTaskButton.tsx
  src/components/writeRetro/Frame.tsx
  src/components/writeRetro/Message.tsx
  src/components/writeRetro/Task.tsx
  src/components/writeRetro/TaskMessage.tsx
  src/components/writeRetro/Title.tsx
  src/components/writeRetro/WriteRetroActionItems.tsx
  src/components/writeRetro/WriteRetroKudos.tsx
  src/components/writeRetro/WriteRetroToImprove.tsx
  src/components/writeRetro/WriteRetroWentWell.tsx
  src/pages/WriteRetroTeamPage.tsx
  src/styles/writeRetroStyles/AddTaskButton.style.ts
  src/styles/writeRetroStyles/Frame.style.ts
  src/styles/writeRetroStyles/Label.style.ts
  src/styles/writeRetroStyles/Message.style.ts
  src/styles/writeRetroStyles/Task.style.ts
  src/styles/writeRetroStyles/TaskMessage.style.ts
  src/styles/writeRetroStyles/WriteRetroFrame.style.ts
  src/styles/writeRetroStyles/WriteRetroTitle.style.ts
  yarn.lock
Labels: enhancement, FE

#66 [FE][Fix] imageUpload 컴포넌트 수정
  src/components/createRetro/modal/ImageUpload.tsx
Labels: FE

#70 #52 [Fix] 버튼 active 상태 유지
  src/components/RetroListHaveSth/RetroListContentsFilter.tsx
  src/components/RetroListHaveSth/RetroListViewButton.tsx
  src/styles/RetroListHaveSth/RetroListContentsFilter.style.ts
  src/styles/RetroListHaveSth/RetroListSortButton.style.ts
  src/styles/RetroListHaveSth/RetroListViewButton.style.ts
Labels: FE

#73 #58 [Feature] RetroList 검색 기능 구현
  src/components/RetroListHaveSth/ContentsList.tsx
  src/components/RetroListHaveSth/RetroListSearch.tsx
  src/pages/RetroListHaveSthPage.tsx
Labels: FE

#75 #60 [Feature] RetroList 회고 진행 여부 버튼 퍼블리싱
  src/assets/ArrowDown.png
  src/assets/ArrowUp.png
  src/assets/Newest.png
  src/assets/Oldest.png
  src/assets/Progress_All.png
  src/components/RetroListHaveSth/BookmarkButton.tsx
  src/components/RetroListHaveSth/ControlBar.tsx
  src/components/RetroListHaveSth/ProgressButton.tsx
  src/components/RetroListHaveSth/SortButton.tsx
  src/pages/RetroListHaveSthPage.tsx
  src/styles/RetroListHaveSth/ControlBar.style.ts
  src/styles/RetroListHaveSth/ProgressButton.style.ts
Labels: FE

#82 [FE][Feature] Register Page 퍼블리싱
  package.json
  src/App.tsx
  src/components/layout/parts/MainNavBar.tsx
  src/components/login/EmailInput.tsx
  src/components/login/LoginModal.tsx
  src/components/login/PasswordInput.tsx
  src/components/user/EmailAuthentication.tsx
  src/components/user/EmailForm.tsx
  src/components/user/EmailInput.tsx
  src/components/user/GoogleLoginButton.tsx
  src/components/user/KakaoLoginButton.tsx
  src/components/user/LoginButton.tsx
  src/components/user/PasswordInput.tsx
  src/pages/CreateRetroPage.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/styles/login/LoginModal.style.ts
  src/styles/user/LoginPage.style.ts
  src/styles/user/RegisterPage.style.ts
  yarn.lock
Labels: FE

#85 [FE][Fix] conflict 해결 과정 중 지워진 package.json 오타 수정
  package.json
  yarn.lock
Labels: FE

#87 [FE][Feature] CreateRetro UI 수정
  src/components/createRetro/DescriptionBox.tsx
  src/components/createRetro/PersonalRetroDescription.tsx
  src/components/createRetro/TeamRetroDescription.tsx
  src/styles/createRetro/CreateButtonBox.style.ts
  src/styles/createRetro/Description.style.ts
  src/styles/createRetro/DescriptionBox.style.ts
Labels: FE

#90 #61 [Feature] RetroList 북마크 버튼
  src/assets/BookmarkIcon_Y.png
  src/components/RetroListHaveSth/BookmarkButton.tsx
  src/components/RetroListHaveSth/ControlBar.tsx
  src/pages/RetroListHaveSthPage.tsx
  src/styles/RetroListHaveSth/BookmarkButton.styles.ts
  src/styles/RetroListHaveSth/ControlBar.styles.ts
Labels: FE

#99 [FE][Feature] CreateRetro 설명 작성창 추가
  src/components/createRetro/modal/CreateModal.tsx
  src/components/createRetro/modal/DescriptionInput.tsx
  src/styles/createRetro/modal/CreateModal.style.ts
Labels: FE

#102 [FE][Feature] SurveyPage 퍼블리싱
  src/App.tsx
  src/components/survey/AgeInput.tsx
  src/components/survey/CityRadio.tsx
  src/components/survey/GenderRadio.tsx
  src/components/survey/JobSelect.tsx
  src/components/survey/PathRadio.tsx
  src/components/survey/PurposeCheckbox.tsx
  src/index.css
  src/pages/SurveyPage.tsx
  src/styles/survey/AgeInput.style.ts
  src/styles/survey/CityRadio.style.ts
  src/styles/survey/GenderRadio.style.ts
  src/styles/survey/JobSelect.style.ts
  src/styles/survey/PathRadio.style.ts
  src/styles/survey/PurposeCheckbox.style.ts
  src/styles/survey/SurveyPage.style.ts
Labels: FE

#104 [FE][Chore] packageManager 정의
  .husky/pre-commit
  package-lock.json
  package.json
Labels: FE

#108 [FE][Feature] Invite Team Modal 퍼블리싱
  package.json
  src/App.tsx
  src/components/createRetro/modal/CreateModal.tsx
  src/components/inviteTeam/InviteTeamModal.tsx
  src/styles/inviteTeam/InviteTeamModal.style.ts
  yarn.lock
Labels: FE

#110 :sparkles: Feat : commit 확인
  .eslintcache
  src/components/writeRetro/WriteRetroKudos.tsx
  src/pages/WriteRetroTeamPage.tsx
Labels: FE

#105 Feat: Amplify auth init
  .env
  .github/CODEOWNERS
  package.json
  src/App.tsx
  src/awsConfig.ts
  yarn.lock
Labels: FE
